<?php

namespace Container8wDpI73;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YZFbo00Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yZFbo00' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yZFbo00'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CandidatController::delete' => ['privates', '.service_locator.4XzjmVT', 'get_ServiceLocator_4XzjmVTService', true],
            'App\\Controller\\CandidatController::edit' => ['privates', '.service_locator.4XzjmVT', 'get_ServiceLocator_4XzjmVTService', true],
            'App\\Controller\\CandidatController::index' => ['privates', '.service_locator.WEMvFZ1', 'get_ServiceLocator_WEMvFZ1Service', true],
            'App\\Controller\\CandidatController::show' => ['privates', '.service_locator.4XzjmVT', 'get_ServiceLocator_4XzjmVTService', true],
            'App\\Controller\\CategoriaController::delete' => ['privates', '.service_locator.2OM4L_f', 'get_ServiceLocator_2OM4LFService', true],
            'App\\Controller\\CategoriaController::edit' => ['privates', '.service_locator.2OM4L_f', 'get_ServiceLocator_2OM4LFService', true],
            'App\\Controller\\CategoriaController::index' => ['privates', '.service_locator.6ieTL0P', 'get_ServiceLocator_6ieTL0PService', true],
            'App\\Controller\\CategoriaController::show' => ['privates', '.service_locator.2OM4L_f', 'get_ServiceLocator_2OM4LFService', true],
            'App\\Controller\\EmpresaController::delete' => ['privates', '.service_locator.f9r8_yo', 'get_ServiceLocator_F9r8YoService', true],
            'App\\Controller\\EmpresaController::edit' => ['privates', '.service_locator.f9r8_yo', 'get_ServiceLocator_F9r8YoService', true],
            'App\\Controller\\EmpresaController::index' => ['privates', '.service_locator.ZumzI2X', 'get_ServiceLocator_ZumzI2XService', true],
            'App\\Controller\\EmpresaController::show' => ['privates', '.service_locator.f9r8_yo', 'get_ServiceLocator_F9r8YoService', true],
            'App\\Controller\\OfertaController::delete' => ['privates', '.service_locator.iMwbJZt', 'get_ServiceLocator_IMwbJZtService', true],
            'App\\Controller\\OfertaController::edit' => ['privates', '.service_locator.iMwbJZt', 'get_ServiceLocator_IMwbJZtService', true],
            'App\\Controller\\OfertaController::index' => ['privates', '.service_locator.t7oklxV', 'get_ServiceLocator_T7oklxVService', true],
            'App\\Controller\\OfertaController::show' => ['privates', '.service_locator.iMwbJZt', 'get_ServiceLocator_IMwbJZtService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\CandidatController:delete' => ['privates', '.service_locator.4XzjmVT', 'get_ServiceLocator_4XzjmVTService', true],
            'App\\Controller\\CandidatController:edit' => ['privates', '.service_locator.4XzjmVT', 'get_ServiceLocator_4XzjmVTService', true],
            'App\\Controller\\CandidatController:index' => ['privates', '.service_locator.WEMvFZ1', 'get_ServiceLocator_WEMvFZ1Service', true],
            'App\\Controller\\CandidatController:show' => ['privates', '.service_locator.4XzjmVT', 'get_ServiceLocator_4XzjmVTService', true],
            'App\\Controller\\CategoriaController:delete' => ['privates', '.service_locator.2OM4L_f', 'get_ServiceLocator_2OM4LFService', true],
            'App\\Controller\\CategoriaController:edit' => ['privates', '.service_locator.2OM4L_f', 'get_ServiceLocator_2OM4LFService', true],
            'App\\Controller\\CategoriaController:index' => ['privates', '.service_locator.6ieTL0P', 'get_ServiceLocator_6ieTL0PService', true],
            'App\\Controller\\CategoriaController:show' => ['privates', '.service_locator.2OM4L_f', 'get_ServiceLocator_2OM4LFService', true],
            'App\\Controller\\EmpresaController:delete' => ['privates', '.service_locator.f9r8_yo', 'get_ServiceLocator_F9r8YoService', true],
            'App\\Controller\\EmpresaController:edit' => ['privates', '.service_locator.f9r8_yo', 'get_ServiceLocator_F9r8YoService', true],
            'App\\Controller\\EmpresaController:index' => ['privates', '.service_locator.ZumzI2X', 'get_ServiceLocator_ZumzI2XService', true],
            'App\\Controller\\EmpresaController:show' => ['privates', '.service_locator.f9r8_yo', 'get_ServiceLocator_F9r8YoService', true],
            'App\\Controller\\OfertaController:delete' => ['privates', '.service_locator.iMwbJZt', 'get_ServiceLocator_IMwbJZtService', true],
            'App\\Controller\\OfertaController:edit' => ['privates', '.service_locator.iMwbJZt', 'get_ServiceLocator_IMwbJZtService', true],
            'App\\Controller\\OfertaController:index' => ['privates', '.service_locator.t7oklxV', 'get_ServiceLocator_T7oklxVService', true],
            'App\\Controller\\OfertaController:show' => ['privates', '.service_locator.iMwbJZt', 'get_ServiceLocator_IMwbJZtService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\CandidatController::delete' => '?',
            'App\\Controller\\CandidatController::edit' => '?',
            'App\\Controller\\CandidatController::index' => '?',
            'App\\Controller\\CandidatController::show' => '?',
            'App\\Controller\\CategoriaController::delete' => '?',
            'App\\Controller\\CategoriaController::edit' => '?',
            'App\\Controller\\CategoriaController::index' => '?',
            'App\\Controller\\CategoriaController::show' => '?',
            'App\\Controller\\EmpresaController::delete' => '?',
            'App\\Controller\\EmpresaController::edit' => '?',
            'App\\Controller\\EmpresaController::index' => '?',
            'App\\Controller\\EmpresaController::show' => '?',
            'App\\Controller\\OfertaController::delete' => '?',
            'App\\Controller\\OfertaController::edit' => '?',
            'App\\Controller\\OfertaController::index' => '?',
            'App\\Controller\\OfertaController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CandidatController:delete' => '?',
            'App\\Controller\\CandidatController:edit' => '?',
            'App\\Controller\\CandidatController:index' => '?',
            'App\\Controller\\CandidatController:show' => '?',
            'App\\Controller\\CategoriaController:delete' => '?',
            'App\\Controller\\CategoriaController:edit' => '?',
            'App\\Controller\\CategoriaController:index' => '?',
            'App\\Controller\\CategoriaController:show' => '?',
            'App\\Controller\\EmpresaController:delete' => '?',
            'App\\Controller\\EmpresaController:edit' => '?',
            'App\\Controller\\EmpresaController:index' => '?',
            'App\\Controller\\EmpresaController:show' => '?',
            'App\\Controller\\OfertaController:delete' => '?',
            'App\\Controller\\OfertaController:edit' => '?',
            'App\\Controller\\OfertaController:index' => '?',
            'App\\Controller\\OfertaController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
