<?php

namespace Container8wDpI73;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WEMvFZ1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WEMvFZ1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WEMvFZ1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'candidatRepository' => ['privates', 'App\\Repository\\CandidatRepository', 'getCandidatRepositoryService', true],
        ], [
            'candidatRepository' => 'App\\Repository\\CandidatRepository',
        ]);
    }
}
