<?php

namespace Container8wDpI73;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IMwbJZtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iMwbJZt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iMwbJZt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ofertum' => ['privates', '.errored..service_locator.iMwbJZt.App\\Entity\\Oferta', NULL, 'Cannot autowire service ".service_locator.iMwbJZt": it references class "App\\Entity\\Oferta" but no such service exists.'],
        ], [
            'ofertum' => 'App\\Entity\\Oferta',
        ]);
    }
}
