<?php

namespace Container8wDpI73;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOfertaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.iMwbJZt.App\Entity\Oferta' shared service.
     *
     * @return \App\Entity\Oferta
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.iMwbJZt": it references class "App\\Entity\\Oferta" but no such service exists.');
    }
}
