<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVDjjxqF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVDjjxqF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVDjjxqF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVDjjxqF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVDjjxqF\App_KernelDevDebugContainer([
    'container.build_hash' => 'VDjjxqF',
    'container.build_id' => '96fe5ee9',
    'container.build_time' => 1616060043,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVDjjxqF');
