<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ2Uk2fE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ2Uk2fE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ2Uk2fE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ2Uk2fE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ2Uk2fE\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z2Uk2fE',
    'container.build_id' => '43821bfc',
    'container.build_time' => 1616140024,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ2Uk2fE');
